# name|path|profile|repo|enabled|group
agentsorch|/home/alangomes/actions-runners/agentsorch|python|oalangomes/agentsorch|true|agentsorch
neurotrack-app|/home/alangomes/actions-runners/neurotrack-app|flutter|oalangomes/neurotrack-app|true|neurotrack
neurotrack_ms|/home/alangomes/actions-runners/neurotrack_ms|node|oalangomes/neurotrack_ms|true|neurotrack_ms
ea-fc-sheffield-hub|/home/alangomes/actions-runners/ea-fc-sheffield-hub|python|oalangomes/ea-fc-sheffield-hub|true|fifa
neurotrack_web|/home/alangomes/actions-runners/neurotrack_web|react|oalangomes/neurotrack_web|true|neurotrack
docsneurotrackapp|/home/alangomes/actions-runners/docsneurotrackapp|javascript|oalangomes/docsneurotrackapp|true|neurotrack
roboapostas|/home/alangomes/actions-runners/roboapostas|node|oalangomes/roboapostas|true|roboapostas
neurotrack_ms-2|/home/alangomes/actions-runners/neurotrack_ms-2|node|oalangomes/NeuroTrack_MS|true|neurotrack_ms
neurotrack_ms-3|/home/alangomes/actions-runners/neurotrack_ms-3|node|oalangomes/NeuroTrack_MS|true|neurotrack_ms
agentsorch-2|/home/alangomes/actions-runners/agentsorch-2|python|oalangomes/agentsorch|true|agentsorch
agentsorch-3|/home/alangomes/actions-runners/agentsorch-3|python|oalangomes/agentsorch|true|agentsorch
