# name|path

agentsorch|/home/alangomes/actions-runners/agentsorch
neurotrack-app|/home/alangomes/actions-runners/neurotrack-app
neurotrack_ms|/home/alangomes/actions-runners/neurotrack_ms
ea-fc-sheffield-hub|/home/alangomes/actions-runners/ea-fc-sheffield-hub
neurotrack_web|/home/alangomes/actions-runners/neurotrack_web
docsneurotrackapp|/home/alangomes/actions-runners/docsneurotrackapp
roboapostas|/home/alangomes/actions-runners/roboapostas
